blank_issues_enabled: false
contact_links:
  - name: GreaterDiscord Support Server
    url: https://greaterdiscord.app/invite
    about: The best place to get immediate support.
  - name: Troubleshooting Guide
    url: https://docs.greaterdiscord.app/users/getting-started/troubleshooting
    about: The user troubleshooting guide from the documentation.
